# serverless.yml
service: elden-hub
provider:
  name: aws
  runtime: nodejs14.16
  region: ap-southeast-2

functions:
  ssr:
    handler: handler.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-offline
custom:
  apigwBinary:
    types:
      - "*/*"
